steps:
  - name: deploy
    image: node:lts
    volumes:
      - /data/app:/app
    commands:
      - ls -l /app
      - ls -l /data/app
      - cd /app/tennis/web &&
      - npm install &&
      - npm run build
